eureka:
  client:
    register-with-eureka: false

server:
  port: 8070

spring:
  application:
    name: gateway
  config:
    import:configserver: http://localhost:8082
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: app
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/app/**


